<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <AssemblyName>Striverum</AssemblyName>
    <RootNamespace>Striverum</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\striverum.ico</ApplicationIcon>
    <AssemblyVersion>1.0.4.0</AssemblyVersion>
    <FileVersion>1.0.4.0</FileVersion>
    <Version>1.0.4</Version>
    <PublishRelease>true</PublishRelease>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <NoWarn>$(NoWarn);NU1902</NoWarn>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>embedded</DebugType>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <SelfContained Condition="'$(SelfContained)' == ''">true</SelfContained>
    <PublishDir Condition="'$(PublishDir)' == ''">$(MSBuildThisFileDirectory)..\publish\</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\ggs.png" />
    <None Remove="Assets\RobotoMono-Regular.ttf" />
    <None Remove="Assets\Striverumpreview.png" />
    <None Remove="GameBanana.png" />
    <None Remove="Resources\REDGame.uasset" />
    <None Remove="Resources\REDGame.uexp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome5" Version="2.1.0" />
    <PackageReference Include="gong-wpf-dragdrop" Version="2.3.2" />
    <PackageReference Include="Onova" Version="2.6.2" />
    <PackageReference Include="SharpCompress" Version="0.39.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\GameBanana.png" />
    <Resource Include="Assets\Icons\ggs.png" />
    <Resource Include="Assets\Icons\sounds.png" />
    <Resource Include="Assets\Icons\wips.png" />
    <Resource Include="Assets\RobotoMono-Regular.ttf" />
    <Resource Include="Assets\Striverumpreview.png" />
    <Resource Include="Assets\striverum.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="UI\FetchWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>

    <None Update="Dependencies\quickbms\quickbms_4gb_files.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\quickbms\unreal_tournament_4.bms">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\u4pak\u4pak.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\dwmapi.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\ActorDumperMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\BPML_GenericFunctions\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\BPModLoaderMod\load_order.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\BPModLoaderMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\CheatManagerEnablerMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\ConsoleCommandsMod\Scripts\dump_object.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\ConsoleCommandsMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\ConsoleCommandsMod\Scripts\set.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\ConsoleCommandsMod\Scripts\summon_unloaded_assets.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\ConsoleEnablerMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\jsbLuaProfilerMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\Keybinds\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\LineTraceMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\mods.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\shared\Types.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\shared\UEHelpers\UEHelpers.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\Mods\SplitScreenMod\Scripts\main.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\UE4SS-settings.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\ue4ss\ue4ss.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\umodel\LICENSE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\umodel\SDL2_64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dependencies\umodel\umodel_64.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Cache\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="UI\ChoiceWindow.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\ConfigurePaksWindow.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="UI\FetchWindow.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="UI\AltLinkWindow.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

</Project>
